### ISSUE TITLE
Objects remain in memory after cursor operation.

### ISSUE THREAD

**Issue by matvp91** [mongodb/mongo-php-library#318] opened 2016-12-23 10:41 UTC
My application requires a large data set to be fetched in chunks, each chunk processed separately and stored in a caching mechanism. Let's say I need to process over a million documents, chunked in batches of 50.000 documents each. I accomplish this by creating separate cursors with a limit of 50k, and a skip of N*50k. It came to my attention that memory gets stacked up.

I wrote a quick test case to illustrate the fact that data remains in memory, when all pointers have been dereferences, and the garbage collector came by to clear loose pointers. The first test case uses the legacy driver (which I've reproduced with the mongod.so later).
```php
$client = new MongoClient('mongodb://localhost:27017/', [
    'username' => 'root'
]);

var_dump(memory_get_usage());

$collection = $client->test_db->selectCollection('statements');

$cursor = $collection->find(array(), array())->limit(50000);

$result = iterator_to_array($cursor, false);

unset($cursor);
unset($collection);
unset($client);
unset($result);

gc_collect_cycles();
var_dump(memory_get_usage());
```

Which results in the following output:
```
int(220432)
int(16931864)
```
Meaning, after the garbage collection came by, there are ~16711432 (~16MB) bytes left in memory that are of no use.

Now, I am aware that this is the legacy driver, thus I decided to check whether memory is handled differently on the latest driver. The second test case uses the latest mongodb.so PHP extension, and chunks the cursor results.
```php
$client = new MongoDB\Client('mongodb://localhost:27017/');

$collection = $client->test_db->statements;

var_dump(memory_get_usage());

$max = 10000;
$i = 0;
do {
    $cursor = $collection->find(array(), array(
        'limit' => $max,
        'skip' => $i++ * $max
    ));

    $result = iterator_to_array($cursor, false);
    $next = count($result) > 0;

    unset($cursor);
    unset($result);

    gc_collect_cycles();
    var_dump(memory_get_usage());
} while ($next);
```
The result, which halts at the 15th iteration (in order to avoid a memory overflow), looks like this:
```
int(273592)
int(25655616)
int(34726080)
int(43798600)
int(52933952)
int(62130608)
int(71279608)
int(80451848)
int(89597504)
int(98797848)
int(107977184)
int(117144760)
int(126304616)
int(135547200)
int(144829616)
int(154014840)
```
Memory stacks up, when both the cursor and the result are no longer referenced, until it overflows.
```
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 80 bytes) in /data/public/mongodb_t1/vendor/mongodb/mongodb/src/Model/BSONDocument.php on line 68
```
With a million documents that need to be processed, each chunked at 50k, there are 20 iterations needed but it exceeds the max. memory due to the behavior I wrote above.

* MongoDB: 3.0.14
* mongo.so: 1.6.14
* mongodb.so: 1.2.2
* php: 5.5.9

Is there a reason why, after dereferencing, the objects remain in memory?

**Comment by moderndeveloperllc** [comment] 2016-12-24 02:25
@matvp91 This may sound silly, but can you run this with `$i` starting higher up? For some reason I seem to remember something about memory usage and `skip`. I would be curious to know if starting with `$i = 10` gives you a higher memory reading right at the start than `$i = 0`.

**Comment by jmikola** [comment] 2016-12-27 18:48
> Now, I am aware that this is the legacy driver, thus I decided to check whether memory is handled differently on the latest driver.

I'll just focus on the current driver now, as we don't have any intention of maintaining the legacy driver apart from urgent security patches at this point.

> * mongodb.so: 1.2.2
> * php: 5.5.9

I'm not sure how you were able to compile the 1.2.2 driver with PHP 5.5.9, as there is a build error due to `php_date_get_immutable_ce()` missing. This will be fixed for 1.2.3 by https://github.com/mongodb/mongo-php-driver/pull/500.

I attempted reproducing your issue by building the driver from that PR instead of 1.2.2. For reference, my build of PHP 5.5.9 used the following `./configure` flags:

> ./configure --enable-bcmath --enable-cgi --enable-debug --enable-dom --enable-fpm --enable-json --enable-libxml --enable-mbstring --enable-pcntl --enable-phar --enable-posix --enable-readline --enable-session --enable-xsl --enable-xml --with-curl --with-pear --with-zlib --with-openssl

I was not able to observe any leaks after filling a `test_db.statements` collection with one million documents (e.g. `{ "_id": 1 }`, `{ "_id": 2 }`) and running the query script you provided from the CLI environment. The import script I used was:

```php
<?php

require 'vendor/autoload.php';

$client = new MongoDB\Client;
$collection = $client->test_db->statements;
$collection->drop();

$documents = [];

for ($i = 0; $i < 1000000; $i++) {
    $documents[] = ['_id' => $i];
}

$collection->insertMany($documents);
```

When running your query script, the first `memory_get_usage()` dump prints `int(849440)`. That value then increases to `int(1932640)` after the first iteration and remains fixed at that value for the duration of the script.

I also ran your query script through Valgrind (see: [Generating a Valgrind Log](https://bugs.php.net/bugs-getting-valgrind-log.php)), which turned up no leaks:

```
$ USE_ZEND_ALLOC=0 valgrind --tool=memcheck --leak-check=full php gh318.php &> gh318.txt
```

This analysis produced the following abridged log (I replaced a bunch of `int(0)` lines with `...`), which includes output from both Valgrind and your script:

```
==10937== Memcheck, a memory error detector
==10937== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==10937== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==10937== Command: php find.php
==10937== 
int(0)
...
int(0)
==10937== 
==10937== HEAP SUMMARY:
==10937==     in use at exit: 74,853 bytes in 10 blocks
==10937==   total heap usage: 21,061,573 allocs, 21,061,563 frees, 1,276,231,246 bytes allocated
==10937== 
==10937== LEAK SUMMARY:
==10937==    definitely lost: 0 bytes in 0 blocks
==10937==    indirectly lost: 0 bytes in 0 blocks
==10937==      possibly lost: 0 bytes in 0 blocks
==10937==    still reachable: 0 bytes in 0 blocks
==10937==         suppressed: 74,853 bytes in 10 blocks
==10937== 
==10937== For counts of detected and suppressed errors, rerun with: -v
==10937== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

```

Note that `get_memory_usage()` reports `int(0)` because we've disabled the [Zend memory manager](http://php.net/manual/en/internals2.memory.management.php) for debugging purposes.

**Comment by enleur** [comment] 2017-02-14 12:51
I have the same issue. Memory is not freed after an operation. It looks like reserved memory, if you run in a sequance operations that consume 160mb, 80mb and 50mb it will remain on 160mb after all

MongoDB: 3.4.2
mongodb.so: 1.22/1.23/1.2.5
php: 7.1

**Comment by Steveb-p** [comment] 2017-02-14 13:47
@enleur PHP does not free process memory. It's not related to mongo library. Once system allocates memory to PHP it's stuck there until process terminates. If there we're a memory leak you would see memory incrementaly taking more & more.

**Comment by jmikola** [comment] 2018-02-27 16:52
Closing this due to inactivity. We have no outstanding issues for leaks in the extension. If the issue persists on the 1.4.x version of the extension, please open an issue in the [PHPC](https://jira.mongodb.org/projects/PHPC/summary) JIRA project.

**Closed by jmikola** 2018-02-27 16:52 UTC
Labels: waiting-for-user
