### ISSUE TITLE
Support update commands

### ISSUE THREAD

**Issue by qRoC** [mongodb/mongo-php-library#384] opened 2017-07-03 15:35 UTC
[`Database::command`](https://github.com/mongodb/mongo-php-library/blob/master/src/Database.php#L165) call driver function [`MongoDB\Manager::selectServer`](https://github.com/mongodb/mongo-php-driver/blob/master/src/MongoDB/Manager.c#L447), but she [called](https://github.com/mongodb/mongo-php-driver/blob/master/src/MongoDB/Manager.c#L464) `mongoc_client_select_server` with `for_writes=false`. So write commands(findandmodify, etc) will not work.

`Database::command` used in Doctrine(doFindAndUpdate, and other).
Need check command type, and set readPreference as primary(this is a crutch).

**Comment by jmikola** [comment] 2017-07-05 18:55
The [extension](https://github.com/mongodb/mongo-php-driver) rightfully passes `for_writes=false` as that is required for `mongoc_client_select_server()` to honor the read preference parameter.

Do you have a standalone script that demonstrates an issue with executing a write command (e.g. `findAndModify`)?

**Comment by qRoC** [comment] 2017-07-06 10:39
> The extension rightfully passes for_writes=false as that is required for mongoc_client_select_server() to honor the read preference parameter.
Yes, but `command` used not only for read requests.

> Do you have a standalone script that demonstrates an issue with executing a write command (e.g. findAndModify)?

1. 
   `$ db.getMongo().setReadPref('nearest') # secondary, secondaryPreferred`

2. Run code(symfony+ doctrine + library `alcaeus/mongo-php-adapter`):

```php
$documentManager = $this->getContainer()->get('doctrine.odm.mongodb.document_manager');
        $documentManager->createQueryBuilder(MyDocument::class)
            ->findAndUpdate()
            ->returnNew(false)
            ->field('myField')->equals(1)
            ->field('MyIncField')->inc(1)
            ->upsert(true)
            ->getQuery(['w' => 0, 'j' => false])
            ->execute();
```

This code send to method `command` next data:

```php
array (
  'findandmodify' => 'my_document',
  'query' => stdClass::__set_state(array( 'myField' => 1, )),
  'update' => 
  stdClass::__set_state(array('$inc' => array ('MyIncField' => 1,),
  )),
  'w' => 0,
  'j' => false,
  'new' => false,
  'upsert' => true,
)
```

For this command need use primary server

**Comment by jmikola** [comment] 2017-07-06 13:54
> Yes, but `command` used not only for read requests.

If we specified `for_writes=false` for `mongoc_client_select_server()`, [`MongoDB\Driver\Manager::selectServer()`](http://php.net/manual/en/mongodb-driver-manager.selectserver.php) would only ever select a primary server and the read preference argument would never be used.

Ensuring that you execute a write command on a primary server is not the responsibility of the extension. By design, it allows users to select _any_ server and execute queries, commands, or bulk write operations. If you look at the code in the PHP library (this repository), write operations [explicitly select a server using the primary read preference](https://github.com/mongodb/mongo-php-library/blob/323d64584f0611611cb3385496e3ac1a180b0f83/src/Collection.php#L576).

If commands were instead executed via [`MongoDB\Driver\Manager::executeCommand()`](http://php.net/manual/en/mongodb-driver-manager.executecommand.php), which does server selection internally, it would still be the responsibility of the caller to provide a primary read preference for a write command.

> `$ db.getMongo().setReadPref('nearest') # secondary, secondaryPreferred`
>
> Run code(symfony+ doctrine + library `alcaeus/mongo-php-adapter`):

You're mixing MongoDB shell syntax with PHP here, but I assume you were implying that your connection in PHP specifies a `nearest` read preference as its top-level default. In this case, it's still the responsibility of the library to set a primary read preference for write commands.

**Comment by jmikola** [comment] 2017-07-06 14:18
I looked into this a bit more with @alcaeus and it appears to be an outstanding bug in [Doctrine MongoDB](https://github.com/doctrine/mongodb), as it does not enforce a primary read preference for write operations executed through its Query class. At the moment, I also think it may date back to the legacy `mongo` extension.

I'll follow up with a PR soon and hopefully you can test that to see if it resolves the issue.

**Comment by qRoC** [comment] 2017-07-06 18:49
> as it does not enforce a primary read preference for write operations executed through its Query class

How is this possible if the parameter `readPreference` is taken from connections settings(`MongoClient`), and setter of `readPreference` in `MongoDB` has a private access level.

**Comment by qRoC** [comment] 2017-07-06 18:52
Ow, sorry. This work in mongo-php-library, but not in alcaeus/mongo-php-adapter.

**Comment by alcaeus** [comment] 2017-07-06 18:56
Yes, there are two issues coming together here: one would be Doctrine MongoDB not applying a read preference of `RP_PRIMARY` when executing commands that should be run on the primary. The legacy driver forced a primary read preference on some commands, a behavior that wasn't replicated in mongo-php-adapter (see alcaeus/mongo-php-adapter#181).

**Comment by alcaeus** [comment] 2017-07-07 05:38
@qRoC I've merged the fix into doctrine/mongodb, could you give `dev-master` a spin and let us know whether that fixes the problem for you?

**Comment by qRoC** [comment] 2017-07-07 06:27
Sorry, I can't use dev branch in prod environment.

**Comment by jmikola** [comment] 2017-07-08 14:11
Closing this as it's being tracked in referenced issues:

 * https://github.com/doctrine/mongodb/pull/297
 * https://github.com/alcaeus/mongo-php-adapter/issues/181

**Closed by jmikola** 2017-07-08 14:11 UTC
