### ISSUE TITLE
What is the best alternate of hasNext & getNext?

### ISSUE THREAD

**Issue by ziyaindia** [mongodb/mongo-php-library#704] opened 2019-12-30 06:22 UTC
I have used MongoClient in one of my application.
My old code having hasNext & getNext in my functions.
Please suggest me for the bbest alternative for these two functions.
Thanks in Advance

**Comment by jmikola** [comment] 2019-12-30 15:39
Closing this as a duplicate of https://github.com/mongodb/mongo-php-library/issues/703. I realize the question above is a bit different than the "fatal error" reported in #703, but this could have easily been a comment on the original issue.

**Closed by jmikola** 2019-12-30 15:39 UTC
