### ISSUE TITLE
Natural sort error

### ISSUE THREAD

**Issue by mrblackus** [mongodb/mongo-php-library#283] opened 2016-11-16 12:29 UTC
Hi,

My issue looks a lot like #265.
When doing a sort `$natural => -1` on a find, a `Cannot use $-modifiers or empty keys in 'opts'` RuntimeException is raised.

My environment is:
PHP: 7.0.12
Library: 1.0.3
Mongodb: 3.2
Extension: mongodb-1.2.0alpha3

```php
$collection->find([], [ 'sort' => [ '$natural' => -1 ]]);
```

Maybe I'm doing something wrong, or is it a bug?

**Comment by moderndeveloperllc** [comment] 2016-11-16 14:12
@mrblackus It looks like that was [fixed in libmongoc 1.5.0-rc4](https://github.com/mongodb/mongo-c-driver/commit/971af90ac2883690090f21ebd468904fdeae7b69). The current driver appears to utilize 1.5.0-rc3. You might be able to get them to bump that to rc4 if you open a ticket over at https://github.com/mongodb/mongo-php-driver/issues.

**Comment by jmikola** [comment] 2016-11-16 14:28
Indeed, this is also caused by [CDRIVER-1692](https://jira.mongodb.org/browse/CDRIVER-1692). The next extension release will bump the libmongoc version to 1.5.0-rc4 or the stable release if it's available by then. No need to open another issue on the extension repository.

**Comment by mrblackus** [comment] 2016-11-16 14:29
Thanks for your quick answers!

**Comment by moderndeveloperllc** [comment] 2016-11-16 14:30
@jmikola Is there a timeline for the next 1.2.0 release, or just "when ready"?

**Comment by jmikola** [comment] 2016-11-16 14:40
@moderndeveloperllc: 1.2.0 is tracking the MongoDB 3.4 release, as is library version 1.1.0. I don't have any hard dates, but we're getting there based on the recent server release candidates.

**Comment by jmikola** [comment] 2016-11-30 18:50
@mrblackus : [1.2.0](https://github.com/mongodb/mongo-php-driver/releases/tag/1.2.0) of the PHP driver has been released, which includes libmongoc 1.5.0. Please upgrade and report back if the issue is resolved.

The 1.0.3 library version is compatible with the 1.2.0 extension version, so there should be no need to upgrade the library for this issue.

**Closed by jmikola** 2016-11-30 18:50 UTC
Labels: bug
