### ISSUE TITLE
Using the mongo-php-library with 7.3

### ISSUE THREAD

**Issue by jalite1991** [mongodb/mongo-php-library#692] opened 2019-11-01 15:19 UTC
Hello, when running 
`
composer require mongodb/mongodb
`

There is mdanter/ecc in dependencies of an old version, that required php 7.2 max.
So when i'm trying to add the mongo-php-library library to my project, i receive and error:
- mdanter/ecc v0.4.5 requires php >=5.6.0, <7.2 -> your PHP version (7.3.0) does not satisfy that requirement.

The fully php 7.* support for this library was arrived in release PHPECC v0.5.0.

Do you think you guys can add the upgraded mdanter/ecc in your library.

### Environment
PHP: 7.3.x
MAMP: 5.3
MongoDB Atlas.

**Comment by jmikola** [comment] 2019-11-01 16:49
This library has never had any dependency on [mdanter/ecc](https://packagist.org/packages/mdanter/ecc). Looking at [dependents of mdanter/ecc](https://packagist.org/packages/mdanter/ecc/dependents), I don't believe we have any relation to those packages either. This appears to be an issue with your project's dependency chain.

Note that the current stable branch of this library accepts PHPUnit ^5.7.27, ^6.4, or ^8.3 (see: https://github.com/mongodb/mongo-php-library/commit/1c74f44e0a9626158fc35e239a94bff739934dae). These dependencies are also covered by our CI environments, which span PHP 5.6 through 7.4.

I expect the conflict you're seeing may be due to [mdanter/ecc 0.4.5](https://packagist.org/packages/mdanter/ecc#v0.4.5) requiring a PHP version between 5.6 and 7.1 (inclusive) and a PHPUnit version of either 4.1.x or 5.0.x. That may conflict with the mongodb/mongodb library depending on a new PHPUnit version, which may be leaving your project with an unmet dependency (the PHP version in this case).

You may have a few options to move forward. [mdanter/ecc 0.5.2](https://packagist.org/packages/mdanter/ecc#v0.5.2) appears to be the latest stable version and requires PHP ^7.0 and PHPUnit ^6.0, which should overlap with our dependencies. If mdanter/ecc is not a direct dependency of your project, this might be outside of your control, though.

Alternatively, you can omit development packages with `composer install` via the [`--no-dev`](https://getcomposer.org/doc/03-cli.md#install-i) option. If your project is only _using_ this package and not running its test suite, there's probably no need for you to require our development packages (PHPUnit and a compatibility bridge from Symfony as of our 1.5.x branch).

**Comment by alcaeus** [comment] 2019-12-13 15:23
Closing as this is not an issue caused by this package but rather by a third-party package.

**Closed by alcaeus** 2019-12-13 15:23 UTC
