### ISSUE TITLE
Cant connect to atlas - ConnectionTimeoutException: No suitable servers

### ISSUE THREAD

**Issue by thenoblenewbie** [mongodb/mongo-php-library#546] opened 2018-06-26 15:12 UTC
Hi when trying to connect to MongoDB Atlas via PHP and write a simple document I get the following error: 

>   Fatal error: Uncaught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found: serverselectiontimeoutms timed out: [connection closed calling ismaster on 'test-shard-00-00-waf4c.mongodb.net:27017'] in /Applications/AMPPS/www/mongodb/liveserver.php:63

Here is my code trying to connect and bulk write a document:

```
$manager = new MongoDB\Driver\Manager("mongodb://admin:admin@test-shard-00-00-rbgc.mongodb.net:27017/db?ssl=false&replicaSet=test-shard-0&authSource=admin&serverSelectionTryOnce=false");

var_dump($manager);

$bulk = new MongoDB\Driver\BulkWrite;

$bulk->insert(['x' => 1]);
$manager->executeBulkWrite('db.collection', $bulk);
```

  

When I var_dump the $manager I get:

`    object(MongoDB\Driver\Manager)#1 (2) { ["uri"]=> string(64) "admin:admin@test-shard-00-00-rbgc.mongodb.net:27017/" ["cluster"]=> array(0) { } }`

**Some additional information:**
I am using MongoDB Atlas and connecting to it via compass works great, I have whitelisted my IP and also allowed all ips to have access to the cluster. 
I am using MacOS, PHP 7.1, any idea on what causes this problem and if its a driver issue?
(the above code works perfectly with no errors when tested on local installation of mongodb)

Thank you in advance for your time and help.

**Comment by jmikola** [comment] 2018-06-26 17:29
> I am using MongoDB Atlas and connecting to it via compass works great

Are you using the exact same connection string with Compass? I ask because it includes `ssl=false`, and I believe Atlas requires SSL.

Since you're using macOS, I'll also note that 1.4.x currently has a bug that may lead to dropping previously persisted connections. This is likely to come up in a web SAPI, but I don't expect you'll run into it from a CLI environment unless it's a long-running script. See https://github.com/mongodb/mongo-php-driver/issues/855#issuecomment-398801444 and https://github.com/mongodb/mongo-php-driver/issues/791#issuecomment-383328627 for more information. That issue should be addressed in [1.5.0](https://pecl.php.net/package/mongodb/1.5.0), which was just tagged today (formal announcement due tomorrow).

**Comment by thenoblenewbie** [comment] 2018-06-26 18:30
I have tried the exact same code on a windows machine using 1.4.x and it works, so its likely this MacOS bug, that you mentioned.

In order to update to newest (1.5.x) version on mac do I need to just replace the old .so file with the new one and restart apache right?

Thank you very **VERY** much for your fast response.

**Comment by jmikola** [comment] 2018-06-26 19:30
The CLI script in https://github.com/mongodb/mongo-php-driver/issues/791#issuecomment-383936108 can be used to determine if you are actually encountering [PHPC-1169](https://jira.mongodb.org/browse/PHPC-1169) or not.

I'd still appreciate a response to my question about using the same connection string with Compass, as I'm fairly certain that Atlas requires SSL for its connections. It's possible that Compass may have some internal logic that silently enables SSL, although that would be unexpected.

> In order to update to newest (1.5.x) version on mac do I need to just replace the old .so file with the new one and restart apache right?

You can follow the [PECL install process](http://php.net/manual/en/mongodb.installation.pecl.php) in the manual. PECL should install the `mongodb.so` file for you, provided that you use the `pecl` binary corresponding to your PHP runtime (e.g. MAMP and Homebrew would each have their own `pecl` and `phpize` commands, which should know about their respective PHP environments). After installing the new `mongodb.so` file, you may need to restart Apache to ensure the new module is loaded.

**Comment by thenoblenewbie** [comment] 2018-06-27 16:17
I used the same connection string in compass and it worked fine, also in compass there is an option to connect via SSL or unvalidated (insecurely).

**Comment by jmikola** [comment] 2018-06-27 19:35
> I used the same connection string in compass and it worked fine, also in compass there is an option to connect via SSL or unvalidated (insecurely).

I reached out to the Compass developers and they confirmed that it does actually have logic to detect Atlas connection strings and will override `ssl=false` and set other appropriate SSL options (e.g. certificates) if needed.

In any event, I would certainly advise removing `ssl=false` from any Atlas connection string being used with the PHP driver. We have no logic to override that option and will end up trying to open a non-SSL connection to Atlas, which will most certainly fail.

**Closed** 2018-06-30 10:45 UTC
Labels: waiting-for-user

**Comment by bujardeari** [comment] 2019-04-11 12:23
I have a very similiar issue. I have php docker image on kubernetes , and every second time i deploy the image and the container is restarted , mongo connection fails with the same errors message as the above. If i only restart the container right after , then it works. It is really strange. Something to do with Mongo Atlass still haing a connection open and the new try failing ?

**Comment by jmikola** [comment] 2019-04-11 14:33
@bujardeari: Rather than comment on closed issues, it'd be preferable to open a new issue describing your problem and then link back to the old thread(s) for context. This also applies to the comment you added in https://github.com/mongodb/mongo-php-library/issues/372#issuecomment-482055822.

If I understand your problem correctly, the connection cannot be established after restarting the container once as part of your deployment, but restarting it a _second_ time after deployment resolves the issue. This does not sound like anything we have control over in the PHP driver if the PHP process itself is being restarted (i.e. state is being cleared entirely).

I'm not aware of any restrictions within Atlas for accepting multiple connections for the same host, given that would interfere with common PHP deployments (e.g. FPM worker pools) and connection pooling on other drivers. If you're hitting connection _limits_ in Atlas (each tier has its own limits), that's another issue and likely something the support team could identify; however, I wouldn't think limits are an issue if a second restart of the container fixes the problem. It's possible that the root cause rests in the network configuration or container stack. If you have access to [Atlas Support](https://www.mongodb.com/cloud/atlas/faq#support) that may be a better channel to investigate this, as that team may have more awareness of Kubernetes-related issues.

**Comment by SashaDesigN** [comment] 2020-02-20 17:39
For me simply helped updating on mondodb php driver

**Comment by Masihgh** [comment] 2022-03-26 05:49
> For me simply helped updating on mondodb php driver

Thanks a lot for this answer! ?Thats true 
i update driver as 1.11.0 to 1.13.0
