### ISSUE TITLE
How to disable connection pool in php7?

### ISSUE THREAD

**Issue by udoless** [mongodb/mongo-php-library#238] opened 2016-09-08 03:07 UTC
When I use MongoDB\Driver, mongo always creating a lot of connections and staying for a long time. How to disable this feature? I just want a short time connection. Thanks.

**Comment by jmikola** [comment] 2016-09-08 15:18
Duplicate of https://github.com/mongodb/mongo-php-driver/issues/393.

For what it's worth, all connection management is handled in the underlying extension and not the library.

**Closed by jmikola** 2016-09-08 15:18 UTC
