### ISSUE TITLE
cursor session issue

### ISSUE THREAD

**Issue by 719media** [mongodb/mongo-php-library#517] opened 2018-03-27 23:52 UTC
Versions:
mongodb-php 1.4.2
mongodb-php-library 1.3.1
PHP 7.1.13
mongod version 3.6.3
mongo compatibility version is 3.6

I get an error when I run the following shortened code:

```
$tmpConnection = new \MongoDB\Client(
    'mongodb://user:pass@localhost'
);

$testCursor = $tmpConnection->selectDatabase('test')->selectCollection('test')->find();
foreach ($testCursor as $row) {
    ++$recordsScanned;
    echo 'A:' . $recordsScanned . "\n";
}

$testCursor = $tmpConnection->selectDatabase('test')->selectCollection('test')->aggregate([]);
foreach ($testCursor as $row) {
    ++$recordsScanned;
    echo 'B:' . $recordsScanned . "\n";
}
```

Error
```
Cursor session id (142df95e-b30c-409b-ba3c-213d19c8bbee - TDTj2DYnZ/sCdyr5i0hFB2XrtJGBm4wdvewCHRKZkn0=) is not the same as the operation context's session id (55fa9062-7ad7-4416-a169-4b10415a3e5e - TDTj2DYnZ/sCdyr5i0hFB2XrtJGBm4wdvewCHRKZkn0=)
```

The error happens 101 records into the "B" loop

Now, I can replicate this error every time this script is run, but only on a production database. If I do a mongodump and mongoimport into a staging db, and then run the bug script, the error does not reproduce. HOWEVER, one difference between the production database and the staging database: Staging does not use authentication (connection is just `host` instead of `user:pass@host`).

Some other things I can produce with testing:
The error still happens if the first query `find()` is replaced with `aggregate()`
The error does not happen if the second query `aggregate()` is replaced with `find()`
The error does not happen if the second query stores result into a differently named variable `$testCursor2` instead of `$testCursor`, for example. Which is... strange...

**Comment by 719media** [comment] 2018-03-28 00:06
For what it's worth, I enabled security on the staging db, and still no error was thrown

**Comment by jmikola** [comment] 2018-03-28 14:47
Can you share the driver's `phpinfo()` output from the very same PHP process that reproduces this error? Note that CLI and web environments may have different versions of the extension loaded. Likewise, if you were connecting to the staging DB from a local machine, you may have a different version of the extension installed than what is deployed on the production server.

This looks like [CDRIVER-2506](https://jira.mongodb.org/browse/CDRIVER-2506), which was fixed in libmongoc 1.9.3. PHP driver 1.4.2 includes that fix as we bumped our dependencies in https://github.com/mongodb/mongo-php-driver/commit/b55c871b059665ac3dcb92fc88785fe046f803c6.

**Comment by 719media** [comment] 2018-03-29 00:56
Here's the relevant mongo portion from phpinfo:

```
mongodb

MongoDB support => enabled
MongoDB extension version => 1.4.2
MongoDB extension stability => stable
libbson bundled version => 1.9.3
libmongoc bundled version => 1.9.3
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => disabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled

Directive => Local Value => Master Value
mongodb.debug => no value => no value
```

The production and staging servers are running identical versions of:

```
mongodb-php 1.4.2
mongodb-php-library 1.3.1
PHP 7.1.15 (just upgraded today from 7.1.13, problem still persists)
mongod version 3.6.3
mongo compatibility version is 3.6
```

**Comment by 719media** [comment] 2018-03-30 18:14
Great find! Thank you for taking the time to look into this. This is causing some headaches. I also ran into the same problem with just a single query using aggregate, and having that variable passed into a streaming response in php... probably same thing, so that one can't be solved with just using a new variable name... will be great to get this fixed. Thank you

**Comment by jmikola** [comment] 2018-04-19 15:33
[1.4.3](https://github.com/mongodb/mongo-php-driver/releases/tag/1.4.3) has been released with the aforementioned fixes.

**Closed by jmikola** 2018-04-19 15:33 UTC
Labels: bug
