### ISSUE TITLE
iterator_to_array($cursor) returns indexed array instead of associative array

### ISSUE THREAD

**Issue by woshicixide** [mongodb/mongo-php-library#264] opened 2016-10-08 07:41 UTC
when i use iterator_to_array($cursor), how could i get associative array which '_id' as key,like older one
thank you

**Comment by jmikola** [comment] 2016-10-11 17:32
Duplicate of https://github.com/mongodb/mongo-php-driver/issues/430.

**Closed by jmikola** 2016-10-11 17:32 UTC
