### ISSUE TITLE
cant install with php 7.0.8 in Ubuntu 16 platform 

### ISSUE THREAD

**Issue by DBARUNNER** [mongodb/mongo-php-library#308] opened 2016-12-07 11:47 UTC
I cant install mongodb driver for php 7.0.8 in Unbuntu 16 with pecl install mongodb it return me pecl command not found

**Comment by Visualq** [comment] 2016-12-07 12:19
This is not a library problem. 

Try installing pecl: 

sudo apt-get install php-pear php-dev

**Comment by jmikola** [comment] 2016-12-07 15:17
Duplicate of https://github.com/mongodb/mongo-php-driver/issues/482.

@DBARUNNER: Please do not create duplicate issues on the driver *and* library projects. Simply use the project that is most relevant to the issue.

**Closed by jmikola** 2016-12-07 15:17 UTC
