### ISSUE TITLE
Issue with error handling for GridFS readable stream

### ISSUE THREAD

**Issue by karptonite** [mongodb/mongo-php-library#608] opened 2019-04-23 19:49 UTC
This is loosely related to issue #579.

When using `openDownloadableStream()` in gridFS, then feeding the resource to `fread`, the GridFS StreamWrapper catches exceptions then triggers errors in `stream_read()`. Then rather than re-throwing the error, it returns `false`.

That means that something like
```php
while ( !feof( $stream ) )
  echo fread( $stream, 8192 );
```
seems to create an infinite loop in the case of an exception such as ` MongoDB\GridFS\Exception\CorruptFileException: Chunk not found for index "0"`. (Setting aside the separate issue of why that exception was hitting in the first place.)

The error is logged, but the execution goes right back to the loop. Now that I know about this, I suppose I could fix it by assigning the results of `fread()` then breaking out of the loop if the result is ever empty while `feof()` is still false, but this was surprising to me. Is there some better way to handle this? I might have expected for the exception to be re-thrown after the error was logged, in which case I would have caught it and handled it myself.

**Comment by karptonite** [comment] 2019-04-23 20:31
Actually, I'm having trouble actually simulating this error. I have the 500,000 error logs for one request to suggest something is going wrong, but I'm not sure the issue is exactly what I've described.

**Comment by karptonite** [comment] 2019-04-23 21:11
Here was my code to work around this issue for now, but it obviously isn't ideal:
```php
while ( !feof( $stream ) ) {
  $result = fread( $stream, 8192 );
  if( !$result && !feof( $stream ) ) {
    throw new Exception( "Error reading data from store" );
  }
  echo $result;
}
```

**Comment by jmikola** [comment] 2019-04-24 15:26
> The error is logged, but the execution goes right back to the loop.

When you say the error is logged, are you referring to your application logging the `E_USER_WARNING` emitted by `trigger_error()` (see: [`StreamWrapper::stream_read()`](https://github.com/mongodb/mongo-php-library/blob/1.4.2/src/GridFS/StreamWrapper.php#L126) for context)?

When implementing GridFS, I tried to follow PHP's [StreamWrapper](https://www.php.net/manual/en/class.streamwrapper.php) guidelines to the letter. Unfortunately, it's doesn't provide guidance on exposing exceptions, since standard IO functions (e.g. `fopen`, `fread`) have their own error-reporting convention (returning boolean `false`) and generally aren't expected to throw.

Our internal behavior of catching exceptions and triggering errors was influenced by the AWS SDK, which [does the same](https://github.com/aws/aws-sdk-php/blob/3.92.1/src/S3/StreamWrapper.php#L915) for many StreamWrapper methods. That said, its [`stream_read()`](https://github.com/aws/aws-sdk-php/blob/3.92.1/src/S3/StreamWrapper.php#L191) does _not_ capture exceptions and return `false` but simply delegates to a PSR method. If we jump over to the [`Psr\Http\Message\StreamInterface::read()`](https://github.com/php-fig/http-message/blob/1.0.1/src/StreamInterface.php#L124) method, it looks like that method will either return a string or throw a RuntimeException. We can look at [`GuzzleHttp\Psr7\Stream::read()`](https://github.com/guzzle/psr7/blob/1.5.2/src/Stream.php#L212) for implementation details.

I'm not convinced that simply changing some of our StreamWrapper methods to start throwing is the correct fix, but I'm open to keeping a dialog open for ways that we can improve this. One idea might be allowing users to register a callable with the Bucket so users can have more control over exception handling. This might allow them to perform their own logging directly, or force the StreamWrapper to throw. I've opened [PHPLIB-426](https://jira.mongodb.org/browse/PHPLIB-426) to track this.

The code you shared in https://github.com/mongodb/mongo-php-library/issues/608#issuecomment-485976263 does look correct, although I'd suggest using a strict comparison for `$result === false` instead of `!$result`. While I wouldn't expect the GridFS stream wrapper to return an empty string via `fread()` under normal circumstances, it also isn't technically an error. This certainly applies to other stream wrappers beyond GridFS as well.

Rather than work with stream functions directly, you use also use [`Bucket::downloadToStream()`](https://docs.mongodb.com/php-library/current/tutorial/gridfs/#downloading-files-with-readable-streams) to write the entire GridFS stream directly to stdout. You can use the `STDOUT` constant from a CLI environment or open `php://stdout` from other SAPIs (as described in [Input/output streams](https://www.php.net/manual/en/features.commandline.io-streams.php)).

As a side note, I noticed that a few Bucket methods that rely on `stream_copy_to_stream()` (including `downloadToStream()`) do not currently check for a `false` return value to indicate an error. Since these methods are well outside of the StreamWrapper API, we can easily throw an exception instead of relying on users to notice a logged `E_USER_WARNING`. I've opened [PHPLIB-425](https://jira.mongodb.org/browse/PHPLIB-425) to address this.

**Comment by karptonite** [comment] 2019-04-24 16:15
> When you say the error is logged, are you referring to your application logging the `E_USER_WARNING` emitted by `trigger_error()` (see: [`StreamWrapper::stream_read()`](https://github.com/mongodb/mongo-php-library/blob/1.4.2/src/GridFS/StreamWrapper.php#L126) for context)?

Correct. we are logging the `E_USER_WARNING` error.

> 
> That said, its [`stream_read()`](https://github.com/aws/aws-sdk-php/blob/3.92.1/src/S3/StreamWrapper.php#L191) does _not_ capture exceptions and return `false` but simply delegates to a PSR method. If we jump over to the [`Psr\Http\Message\StreamInterface::read()`](https://github.com/php-fig/http-message/blob/1.0.1/src/StreamInterface.php#L124) method, it looks like that method will either return a string or throw a RuntimeException. We can look at [`GuzzleHttp\Psr7\Stream::read()`](https://github.com/guzzle/psr7/blob/1.5.2/src/Stream.php#L212) for implementation details.
> 
> I'm not convinced that simply changing some of our StreamWrapper methods to start throwing is the correct fix, but I'm open to keeping a dialog open for ways that we can improve this.

While I'm not sure that throwing a Runtime Exception is correct, that _would_ have prevented the infinite loop we saw.
> 
> The code you shared in [#608 (comment)](https://github.com/mongodb/mongo-php-library/issues/608#issuecomment-485976263) does look correct, although I'd suggest using a strict comparison for `$result === false` instead of `!$result`. While I wouldn't expect the GridFS stream wrapper to return an empty string via `fread()` under normal circumstances, it also isn't technically an error. This certainly applies to other stream wrappers beyond GridFS as well.

I actually tried the strict comparison first, but it didn't seem to work. Somewhere in `fread` it seems that the false returned by `stream_read()` was getting converted to an empty string, hence the loose comparison.

Another change that might fix this, but that might well not be correct: if `stream_eof()` were to return true after such an error, that might solve the problem. For an exception, I'm not sure what is strictly correct for `eof`, but surely in the case of such an error, the user will never want to read anything else from the stream.

**Comment by jmikola** [comment] 2019-04-24 17:47
> I actually tried the strict comparison first, but it didn't seem to work. Somewhere in fread it seems that the false returned by stream_read() was getting converted to an empty string, hence the loose comparison.

If you're able to share a script that initializes `fs.files` and `fs.chunks` collections and can reproduce this, I'd be very interested to take a look and investigate that further.

AFAIK, [`stream_read()`](https://github.com/mongodb/mongo-php-library/blob/1.4.2/src/GridFS/StreamWrapper.php#L129) may return an empty string if called on a writable stream. That logic dates back to https://github.com/mongodb/mongo-php-library/commit/63c2313f4a39529a26930cdd9157d86f7fc1dddf) and is similar to how we return 0 when attempting to write to a readable stream. But based on the [PHP.net docs for `stream_read()`](https://www.php.net/manual/en/streamwrapper.stream-read.php), it seems as if empty string and `false` return values are treated interchangeably. I'd need to look more into how [`fread()`](https://github.com/php/php-src/blob/php-7.3.4/ext/standard/file.c#L1798) infers a read failure and decides to return `false` for its own return value.

> Another change that might fix this, but that might well not be correct: if `stream_eof()` were to return true after such an error, that might solve the problem. For an exception, I'm not sure what is strictly correct for `eof`, but surely in the case of such an error, the user will never want to read anything else from the stream. 

That's a great suggestion. I've opened [PHPLIB-427](https://jira.mongodb.org/browse/PHPLIB-427) to track that.

**Comment by karptonite** [comment] 2019-04-24 18:09
> > I actually tried the strict comparison first, but it didn't seem to work. Somewhere in fread it seems that the false returned by stream_read() was getting converted to an empty string, hence the loose comparison.
> 
> If you're able to share a script that initializes `fs.files` and `fs.chunks` collections and can reproduce this, I'd be very interested to take a look and investigate that further.

I don't have a script that works in that way. Rather, to test this, I just added the following line at the beginning of `readBytes()` in `ReadableStream`:
```
throw \MongoDB\GridFS\Exception\CorruptFileException::missingChunk(0);
```

Then I captured the result of `fread`, and inspected it; it was an empty string, despite the fact that `stream_read()` presumably returned false after capturing the exception.

> That's a great suggestion. I've opened [PHPLIB-427](https://jira.mongodb.org/browse/PHPLIB-427) to track that.

Sounds good!

**Comment by jmikola** [comment] 2020-01-10 15:21
Going to close this issue, but please follow [PHPLIB-427](https://jira.mongodb.org/browse/PHPLIB-427) for any updates.

**Closed by jmikola** 2020-01-10 15:21 UTC

**Comment by ANUKANKSHA** [comment] 2021-02-19 15:21
Hey!
"MongoDB\GridFS\Exception\CorruptFileException: Chunk not found for index "0". (Setting aside the separate issue of why that exception was hitting in the first place.)"

Could you find the reason why this issue was hitting in the first place?

**Comment by jmikola** [comment] 2024-01-30 19:52
Per https://github.com/mongodb/mongo-php-library/pull/1224#discussion_r1470035208, I believe this was ultimately addressed by [PHPLIB-592](https://jira.mongodb.org/browse/PHPLIB-592) in PHPLIB 1.11, when we switched to throwing exceptions in the stream wrapper instead of emitting warnings. With that in mind, no work should be required for [PHPLIB-427](https://jira.mongodb.org/browse/PHPLIB-427) (the original ticket spawned from this thread).
