### ISSUE TITLE
Mongodb replication slow work if one node is down 

### ISSUE THREAD

**Issue by sautchenkov** [mongodb/mongo-php-library#226] opened 2016-08-09 10:48 UTC
Hello! I have Mongodb and replication with 3 nodes. When 3 nodes in working state all read and write queries from PHP perfect working. But if one node, even secondary is down, all queries start to working too slow. 

This is rs.status after shutdown one node:

```
{
        "set" : "rs0",
        "date" : ISODate("2016-08-09T09:10:14.787Z"),
        "myState" : 1,
        "term" : NumberLong(131),
        "heartbeatIntervalMillis" : NumberLong(2000),
        "members" : [
                {
                        "_id" : 1,
                        "name" : "azure:27017",
                        "health" : 1,
                        "state" : 1,
                        "stateStr" : "PRIMARY",
                        "uptime" : 82396,
                        "optime" : {
                                "ts" : Timestamp(1470732998, 1),
                                "t" : NumberLong(131)
                        },
                        "optimeDate" : ISODate("2016-08-09T08:56:38Z"),
                        "electionTime" : Timestamp(1470651502, 1),
                        "electionDate" : ISODate("2016-08-08T10:18:22Z"),
                        "configVersion" : 3,
                        "self" : true
                },
                {
                        "_id" : 2,
                        "name" : "office:27017",
                        "health" : 1,
                        "state" : 2,
                        "stateStr" : "SECONDARY",
                        "uptime" : 82314,
                        "optime" : {
                                "ts" : Timestamp(1470732998, 1),
                                "t" : NumberLong(131)
                        },
                        "optimeDate" : ISODate("2016-08-09T08:56:38Z"),
                        "lastHeartbeat" : ISODate("2016-08-09T09:10:13.909Z"),
                        "lastHeartbeatRecv" : ISODate("2016-08-09T09:10:14.758Z"),
                        "pingMs" : NumberLong(35),
                        "syncingTo" : "azure:27017",
                        "configVersion" : 3
                },
                {
                        "_id" : 3,
                        "name" : "selectel:27017",
                        "health" : 0,
                        "state" : 8,
                        "stateStr" : "(not reachable/healthy)",
                        "uptime" : 0,
                        "optime" : {
                                "ts" : Timestamp(0, 0),
                                "t" : NumberLong(-1)
                        },
                        "optimeDate" : ISODate("1970-01-01T00:00:00Z"),
                        "lastHeartbeat" : ISODate("2016-08-09T09:10:11.475Z"),
                        "lastHeartbeatRecv" : ISODate("1970-01-01T00:00:00Z"),
                        "pingMs" : NumberLong(0),
                        "lastHeartbeatMessage" : "No route to host",
                        "configVersion" : -1
                }
        ],
        "ok" : 1
}

```

This is string in PHP for working with MongoDB:

```
self::$_mongo = new \MongoDB\Client(
'mongodb://localhost,azure,selectel',
[
'replicaSet' => 'rs0',
'w' => 1,
'wtimeoutMS' => 2000,
'journal' => 'false',
'readConcernLevel' => 'local',
'readPreference' => 'nearest'
],
['typeMap' => ['root' => 'array', 'document' => 'array', 'array' => 'array']]
);
```

As I can see in netstat php-fpm try connect to down host in each query:

`tcp        0      1 local.local:52903       selectel:27017          SYN_SENT    9821/php-fpm: pool`

Versions:
PHP 7.0.9
MongoDB 3.2.6
Mongodb driver 1.1.8
Mongo php library 1.0.2

As I think reason is php try to connect down host in each query and waiting some timeout. Why php did this and how I can fix it?

**Comment by lglayal** [comment] 2016-08-09 12:23
Hi,
you may find more information on https://jira.mongodb.org/browse/PHPC-723
you can decrease delay using connectTimeoutMS.
BR.

**Comment by jmikola** [comment] 2016-08-15 07:47
> As I think reason is php try to connect down host in each query and waiting some timeout. Why php did this and how I can fix it?

How often are these queries taking place? If a host is found to be inaccessible, the driver and libmongoc should ignore it for 5 seconds (i.e. [cooldownMS](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#cooldownms)). This is analogous to the blacklisting behavior we had in the legacy driver, to avoid frequent connection attempts we might expect to fail.

Apart from that, I do think experimenting with `connectTimeoutMS` would help. See [this recent mongodb-user post](https://groups.google.com/d/msg/mongodb-user/4kakfomD9eg/fueBVSRiDAAJ) for additional information. In that thread, a user was encountering a delay when an arbiter in his replica set was inaccessible.

**Comment by lglayal** [comment] 2016-08-16 05:55
NB : Blacklisting is efficient when only one process has a given socket pool. With fastcgi processes, each process having it's own sockets pool, the number of issues is more important due to load balancing of requests between processes. If you configured your PHP process to die after N requests (to limit memory leaks for ex.) you will also increase the number of issues. When a host goes down the best solution currently seems to use connectTimeoutMS to limit the time spent in connections. And if such node is down for a long you would have to remove it from replicaset.

**Comment by sautchenkov** [comment] 2016-08-16 10:10
Thanks for information! 

But I can't understand why mongodb php driver can't receive information about available nodes from first node which described in connection string and don't try to connect to unavailable node?

**Comment by lglayal** [comment] 2016-08-16 10:31
A node can be unavailable from other nodes and/or from client, effective 'cluster' configuration depends on outage (process down, host down, network segment down,...). So client first fetch a list of configured/known nodes and tries to connect to, the 'not reachable/healthy' is from client POV. 

The list of available nodes is built dynamically client side. The seed list of nodes is found in your mongodb:// uri, client needs to find the primary using hosts from this list, but also tries to have a view of full replicaset nodes.

Currently :
- mongo driver tries to connect to all nodes, even ones It _may_ not need (needs depend on the kind of request with readPreferences and writeconcern that can change during application lifetime) .
- mongo driver uses blocking connections, that's why you see delays even for nodes you don't need from your application POV. 

Mongo way to handle cluster topology is done both server side and client side as each client maintains connections to all nodes.

**Comment by jmikola** [comment] 2016-09-14 20:58
[1.2.0alpha2](https://github.com/mongodb/mongo-php-driver/releases/tag/1.2.0alpha2) has been released, which includes significant changes to our connection handling and persistence. We've entirely dropped PHP's streams API and now rely on libmongoc for all socket communication, which I expect may resolve a number of outstanding connection handling and timeout issues.

@sautchenkov: Please attempt reproducing your original problem with 1.2.0alpha2 and let us know if the issue has improved. Thanks!

**Comment by sautchenkov** [comment] 2016-11-11 10:09
Hello! We try to use 1.2.0alpha3 and receive another bad behavior:

1. We have 3 nodes with Enforce Keyfile Access Control and User Authentication settings. If all nodes are running all working good.

2. In PHP we have this connection string:
`mongodb://user:password@host-1:60000, user:password@host-2:60000, user:password:@host-3:60000`

3. And if we turn off mongo on the first host in connection string (in this example this is host-1), we receive PHP fatal error no matter write or read operation we try to do:

> PHP message: PHP Fatal error:  Uncaught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (`serverSelectionTryOnce` set): [connection timeout calling ismaster on 'host-1:60000'] [Failed to resolve 'recommerce'] [Failed to resolve 'recommerce'] in /var/www/recommerce/vendor/MongoDB/Collection.php:464

4. We receive this errors not in all requests, we receive this random in ~50% requests. But the amount of this errors growing with time. 

5. If we try to restart php-fpm, after this we receive Fatal in 100% of requests.

6. If some node down but in the connection string in the first place we have running node all working good. 

As we looking with some reason driver try to use first in connection string node, despite the fact that it does not running.

**Comment by jmikola** [comment] 2016-11-14 18:31
This is not a valid connection string:

```
mongodb://user:password@host-1:60000, user:password@host-2:60000, user:password:@host-3:60000
```

I'm not sure if the spaces after each comma were intentional, but those should not be present.

More importantly, you should not be repeating authentication credentials for each host. Credentials are supplied once and are located between "mongodb://" and the first "@" character with the username and password delimited by a colon character (i.e. ":"). After the "@" character, hosts are delimited by commas. If you are repeating authentication credentials, I expect that libmongoc may be parsing your URI with the following hosts:

 * host-1:60000
 * user:password@host-2:60000
 * user:password:@host-3:60000

Since "host-1:60000" is the only valid host, it would make sense that the driver would be able to connect to the replica set if that node was down. When the node was up, the driver likely still couldn't connect to the second and third hosts in your URI string, but it was able to discover the replica set's nodes through its connection to "host-1:60000".

See the [connection string documentation](https://docs.mongodb.com/manual/reference/connection-string/) for additional reference.

**Comment by sautchenkov** [comment] 2016-11-17 09:22
Ohhh, thank you @jmikola now when we rewrite connection string all working good. 
In 1.2.0alpha3 we don't have timeouts as in 1.1.8. Now all working good!

**Comment by jmikola** [comment] 2016-11-17 15:13
@sautchenkov: Excellent! Glad to here the new networking code in 1.2.0 is working well for you. I'll close this out.

**Closed by jmikola** 2016-11-17 15:13 UTC
Labels: needs-alpha2-validation, waiting-for-user
