### ISSUE TITLE
Can Create Database with Newline Character

### ISSUE THREAD

**Issue by rbchasesc** [mongodb/mongo-php-library#649] opened 2019-07-27 00:08 UTC
Today we discovered two databases in our our MongoDB 4.0.3 replica-set that have a trailing newline character. Both databases were created on or about July 8th, 2019. After exhausting all possible angles from the MongoDB shell at creating databases with the trailing newline character, I started investigating PHP code patterns that could result in the errant databases. 

Utilizing MongoDB PHP Library v1.4.2 and MongoDB PHP Driver v1.5.3 currently deployed to our systems since about November 2018, I was **_able_** to recreate the issue by appending a `PHP_EOL`  to the database name, but was **_unable_** to recreate by appending a `\n` string to the database name. 

Below is a simple PHP class that utilizes the library and driver (library is installed via composer and version pinned to 1.4.2). The class executes the various methods by which the database can successfully be created (with `PHP_EOL`) and those which successfully block its creation (with `\n`):
```
<?php

require_once 'vendor/autoload.php';

use MongoDB\Client;

class TestMongoDbNameError
{
    private $config = [
        'username' => '<redacted>',
        'password' => '<redacted>',
        'host' => '<redacted>',       //SRV connection host name
    ];

    public function __construct()
    {
        $client = new \MongoDB\Client(
            "mongodb+srv://{$this->config['username']}:{$this->config['password']}@{$this->config['host']}/",
            [
                'authMechanism' => 'SCRAM-SHA-1',
                'authSource' => 'admin',
                'readConcern' => 'majority',
                'readPreference' => 'primaryPreferred',
                'retryWrites' => 'true',
                'ssl' => false,
                'w' => 'majority',
            ],
            [
                'typeMap' => [
                    'array' => 'array',
                    'document' => 'array',
                    'root' => 'array',
                ],
            ]
        );
        $testDoc = ['Name' => 'Test Document'];

        try {
            $client->selectDatabase('test_schoolcurrent_com\n')->selectCollection('TestCollection')->insertOne($testDoc);
            echo 'selectDatabase HARD \\n ACCEPTED' . PHP_EOL;
        } catch (\Throwable $e) {
            echo "selectDatabase HARD \\n ERROR: {$e->getMessage()}" . PHP_EOL;
            echo $e->__toString() . PHP_EOL . PHP_EOL;
        }

        try {
            $client->selectCollection('test_schoolcurrent_com\n', 'TestCollection')->insertOne($testDoc);
            echo 'selectCollection HARD \\n ACCEPTED' . PHP_EOL;
        } catch (\Throwable $e) {
            echo "selectCollection HARD \\n ERROR: {$e->getMessage()}" . PHP_EOL;
            echo $e->__toString() . PHP_EOL . PHP_EOL;
        }

        try {
            $client->selectDatabase('test_schoolcurrent_com' . PHP_EOL)->selectCollection('TestCollection')->insertOne($testDoc);
            echo 'selectDatabase PHP_EOL ACCEPTED' . PHP_EOL;
        } catch (\Throwable $e) {
            echo "selectDatabase PHP_EOL ERROR: {$e->getMessage()}" . PHP_EOL;
            echo $e->__toString() . PHP_EOL . PHP_EOL;
        }

        try {
            $client->selectCollection('test_schoolcurrent_com' . PHP_EOL, 'TestCollection')->insertOne($testDoc);
            echo 'selectCollection PHP_EOL ACCEPTED' . PHP_EOL;
        } catch (\Throwable $e) {
            echo "selectCollection PHP_EOL ERROR: {$e->getMessage()}" . PHP_EOL;
            echo $e->__toString() . PHP_EOL . PHP_EOL;
        }
    }
}

new TestMongoDbNameError();
```
And here is the output of executing this test:
```
selectDatabase HARD \n ERROR: Invalid namespace specified 'test_schoolcurrent_com\n.TestCollection'
MongoDB\Driver\Exception\BulkWriteException: Invalid namespace specified 'test_schoolcurrent_com\n.TestCollection' in /vagrant/tools/vendor/mongodb/mongodb/src/Operation/InsertOne.php:114
Stack trace:
#0 /vagrant/tools/vendor/mongodb/mongodb/src/Operation/InsertOne.php(114): MongoDB\Driver\Server->executeBulkWrite('test_schoolcurr...', Object(MongoDB\Driver\BulkWrite), Array)
#1 /vagrant/tools/vendor/mongodb/mongodb/src/Collection.php(892): MongoDB\Operation\InsertOne->execute(Object(MongoDB\Driver\Server))
#2 /vagrant/tools/test-mongo-db-name-error.php(40): MongoDB\Collection->insertOne(Array)
#3 /vagrant/tools/test-mongo-db-name-error.php(73): TestMongoDbNameError->__construct()
#4 {main}

selectCollection HARD \n ERROR: Invalid namespace specified 'test_schoolcurrent_com\n.TestCollection'
MongoDB\Driver\Exception\BulkWriteException: Invalid namespace specified 'test_schoolcurrent_com\n.TestCollection' in /vagrant/tools/vendor/mongodb/mongodb/src/Operation/InsertOne.php:114
Stack trace:
#0 /vagrant/tools/vendor/mongodb/mongodb/src/Operation/InsertOne.php(114): MongoDB\Driver\Server->executeBulkWrite('test_schoolcurr...', Object(MongoDB\Driver\BulkWrite), Array)
#1 /vagrant/tools/vendor/mongodb/mongodb/src/Collection.php(892): MongoDB\Operation\InsertOne->execute(Object(MongoDB\Driver\Server))
#2 /vagrant/tools/test-mongo-db-name-error.php(48): MongoDB\Collection->insertOne(Array)
#3 /vagrant/tools/test-mongo-db-name-error.php(73): TestMongoDbNameError->__construct()
#4 {main}

selectDatabase PHP_EOL ACCEPTED
selectCollection PHP_EOL ACCEPTED
```

I'm reporting this as a bug here as it looks like neither the driver nor the library are properly inspecting the characters in the database name for validity relative to the PHP language before handing them off to the underlying libbson or libmongoc. 

**System Info:**
Operating System: Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-131-generic x86_64)
```
db version v4.0.3
git version: 7ea530946fa7880364d88c8d8b6026bbc9ffa48c
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64
```
```
PHP 7.1.23-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 25 2018 06:43:19) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.23-3+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
```

**Comment by alcaeus** [comment] 2019-07-29 06:34
Looking at the [database name restrictions](https://docs.mongodb.com/manual/reference/limits/#naming-restrictions), the list of disallowed characters on a Unix system is `/\. "$` with the null character also not being allowed. This explains why the first calls cause an error: using single quotes does not interpret the `\n` as a newline character, but rather as a literal `\n`. Since the backslash is not allowed in database names, your MongoDB server will throw an error on an operation on the selected namespace.

Changing the single quotes in your example to double quotes yields the same result with `\n` as it does with `PHP_EOL`, which is the expected behaviour as per the name restrictions linked above. I can't comment on whether database names with newline or tab characters makes sense. Maybe @jmikola can provide some insight on that.

**Comment by jmikola** [comment] 2019-07-30 00:30
@alcaeus: Thanks for catching the subtle difference with single- and double-quotes. I missed that when I first took a look at this, but it totally explains the error.

@rbchasesc: The legacy PHP driver (i.e. `mongo` extension) did contain validation logic, as evidenced by tickets such as [PHP-1149](https://jira.mongodb.org/browse/PHP-1449) and [PHP-1469](https://jira.mongodb.org/browse/PHP-1469); however, the current driver/library rely on the server to enforce these restrictions. This is preferable since the allowed characters can vary based on platform, as mentioned in the documentation @alcaeus linked. Additionally, it's possible for these limits to change between server versions.

> I'm reporting this as a bug here as it looks like neither the driver nor the library are properly inspecting the characters in the database name for validity relative to the PHP language before handing them off to the underlying libbson or libmongoc.

For the record, libmongoc also does not validate database and collection names. It happens to use a [128-byte limit](https://github.com/mongodb/mongo-c-driver/blob/1.14.0/src/libmongoc/src/mongoc/mongoc-collection-private.h#L31) for these strings on internal data structures, but ultimately relies on the server to enforce its own validation rules. The exception message you're seeing originates from the server (e.g. [`CommandHelpers::parseNsFullyQualified()`](https://github.com/mongodb/mongo/blob/r4.0.3/src/mongo/db/commands.cpp#L177)).

I'll close this out as the PHP driver and libmongoc are both working as intended.

**Closed by jmikola** 2019-07-30 00:30 UTC

**Comment by rbchasesc** [comment] 2019-07-30 01:22
Thanks guys. I guess we'll have to watch out for errant newlines in our PHP and shell code going forward.
